apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment-prod
  labels:
    app: gateway
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
      env: prod
  template:
    metadata:
      labels:
        app: gateway
        env: prod
    spec:
      containers:
      - name: gateway
        image: ismaamesaa/gateway-api:prod
        ports:
        - containerPort: 3000
        env:
        - name: ORDERS_URL
          value: "http://orders-api-service:8080"
        - name: FLIGHTS_URL
          value: "http://flights-api-service:8080"
