apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment-preprod
  labels:
    app: gateway
    env: preprod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
      env: preprod
  template:
    metadata:
      labels:
        app: gateway
        env: preprod
    spec:
      containers:
      - name: gateway
        image: ismaamesaa/seeker-gateway-api:preprod
        ports:
        - containerPort: 3000
        env:
        - name: ORDERS_URL
          value: "http://orders-api-service-preprod:8080"
        - name: FLIGHTS_URL
          value: "http://flights-api-service-preprod:8080"
