version: '3'
services:
  gateway:
    build: .
    restart: on-failure
    ports:
      - "3000:3000"
    environment:
      - ORDERS_URL=http://orders:8080
      - FLIGHTS_URL=http://flights:8080
      - NODE_ENV=production
    depends_on:
      - orders
      - flights
    networks:
      - app-network

  orders:
    build: ../do2425-ismmeszyo/generated-server
    restart: on-failure
    depends_on:
      - mongodb
    ports:
      - "8082:8080"
    environment:
      - NODE_ENV=production
      - MONGODB_HOST=mongodb
    networks:
      - app-network

  flights:
    build: ../do2425-Alex-Lanero/generated-server
    restart: on-failure
    depends_on:
      - mongodb
    ports:
      - "8081:8080"
    environment:
      - NODE_ENV=production
      - MONGODB_HOST=mongodb
    networks:
      - app-network

  mongodb:
    image: "mongo"
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
