services:
  flights:
    build: ../do2425-Alex-Lanero/generated-server
    restart: on-failure
    depends_on:
      - mongodb
    ports:
      - "8081:8080"
    environment:
      - NODE_ENV=production
      - MONGODB_HOST=mongodb
    networks:
      - app-network

  orders:
    build: ../do2425-ismmeszyo/generated-server
    restart: on-failure
    depends_on:
      - mongodb
    ports:
      - "8082:8080"
    environment:
      - NODE_ENV=production
      - MONGODB_HOST=mongodb
    networks:
      - app-network

  mongodb:
    image: "mongo"
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongodb_data:/data/db

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
