name: Build and Push Docker image

on:
  push:
    branches:
      - develop  # o cualquier rama en la que quieras que se ejecute
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Paso 1: Descargar el repositorio
      - name: Checkout repository
        uses: actions/checkout@v2

      # Paso 2: Iniciar sesión en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Paso 3: Construir la imagen Docker
      - name: Build the Docker image
        run: |
          docker build -t ismaamesaa/order:DO2425-C02 ./generated-server

      # Paso 4: Subir la imagen a Docker Hub
      - name: Push the Docker image
        run: |
          docker push ismaamesaa/order:DO2425-C02
