services:
  flights:
    environment:
      - NODE_ENV=development
      - MONGODB_HOST=mongo
    volumes:
      - "logsvol:/usr/src/app/logs"
  mongo:
    command: ['--logpath', '/var/log/mongodb/db.log']
    volumes:
      - "datavol:/data/db"
      - "logsvol:/var/log/mongodb"
volumes:
  logsvol:
    external: true
  datavol: