openapi: 3.0.3
info:
  version: 1.0.0
  title: Order
  description: Orders 

paths:
  /api/v1/orders:
    get:
      description: Returns all orders
      operationId: getOrders
      responses:
        200:
          description: Order list
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/order'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
    post:
      description: Creates a new order
      operationId: addOrder
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/order'
        description: Order to be created
        required: true
      responses:
        201:
          description: Order
        default:
            description: Unexpected error
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/error'
  /api/v1/orders/{id}:
    get:
      description: Returns a single order by its id
      operationId: findByid
      parameters:
        - required: true
          name: id
          description: id of the order to fetch
          in: path
          schema:
            type: string
      responses:
        200:
          description: Order found by id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/order'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
    put:
      description: Update a order based on its id
      operationId: updateOrder
      parameters:
        - required: true
          name: id
          description: id of the order to update
          in: path
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/order'
        description: Order to be updated
        required: true
      responses:
        204:
          description: Order updated
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
    delete:
      description: Deletes a single order based on its id
      operationId: deleteOrder
      parameters:
        - required: true
          name: id
          description: id of the order to delete
          in: path
          schema:
            type: string
      responses:
        204:
          description: Order deleted
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'

components:
  schemas:
    order:
      type: object
      required:
        - id
        - clienteId
        - productos
        - total
        - entregado
      properties:
        id:
          type: string
        clienteId:
          type: string
        productos:
          type: array
          items:
            type: object
            required:
              - id
              - nombre
              - cantidad
              - precioUnitario
            properties:
              id:
                type: string
              nombre:
                type: string
              cantidad:
                type: integer
              precioUnitario:
                type: number
        cantidadProductos:
          type: number
        total:
          type: number
        entregado:
          type: boolean
    error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
      additionalProperties: true