apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: flights-api
    env: preprod
  name: flights-api-deployment-preprod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flights-api-pod
      env: preprod
  template:
    metadata:
      labels:
        app: flights-api-pod
        env: preprod
    spec:
      containers:
      - name: flights-api-container
        env:
        - name: MONGO_URL
          value: mongodb://mongodb-service:27017
        resources: {}
        image: lanerin/flights-api:preprod
        ports:
        - containerPort: 8080
      restartPolicy: Always
