apiVersion: v1
kind: Service
metadata:
  labels:
    app: flights-api
    env: preprod
  name: flights-api-service-preprod
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: flights-api-pod
    env: preprod
  type: NodePort
