name: Build and Push Docker Image

on:
  push:
    branches:
      - main # Asegúrate de que sea la rama principal correcta

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and tag Docker image
      run: |
        docker build -t lanerin/flights:DO2425-C04 ./generated-server
        docker tag lanerin/flights:DO2425-C04 lanerin/flights:latest

    - name: Push Docker image to Docker Hub
      run: |
        docker push lanerin/flights:DO2425-C04
        docker push lanerin/flights:latest
