apiVersion: v1
kind: Service
metadata:
  labels:
    app: orders-api
  name: orders-api-service
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: orders-api-pod
  type: NodePort
